apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: li-ph-sci-electrochemistry-workspace
  namespace: li-swarm
  labels:
    app: li-ph-sci-electrochemistry
    app.kubernetes.io/name: li-ph-sci-electrochemistry
    app.kubernetes.io/component: goal-directed-agent
    li-langverse.io/sprint: ph-sci-electrochemistry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
