apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: li-libernetes-licontainers-workspace
  namespace: li-swarm
  labels:
    app: li-libernetes-licontainers
    app.kubernetes.io/component: goal-directed-agent
    li-langverse.io/sprint: libernetes-licontainers
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path