apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: li-ph-br-0-lib-browser-workspace
  namespace: li-swarm
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-path
