---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: li-org-observer-supervisor
  namespace: li-swarm
  labels:
    app: li-org-observer-supervisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: li-org-observer-supervisor
  namespace: li-swarm
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: li-org-observer-supervisor
  namespace: li-swarm
subjects:
  - kind: ServiceAccount
    name: li-org-observer-supervisor
    namespace: li-swarm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: li-org-observer-supervisor
