import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { AgentBackend, AgentDefinition, AgentRunOptions, AgentRunResult } from "../types.js";

/**
 * CI-safe mock: no CURSOR_API_KEY, no LLM calls.
 * Writes deterministic markdown + JSON from preflight briefing.
 */
export class MockBackend implements AgentBackend {
  readonly name = "mock" as const;

  async run(
    definition: AgentDefinition,
    _systemPrompt: string,
    userMessage: string,
    options: AgentRunOptions,
  ): Promise<AgentRunResult> {
    const start = Date.now();
    const outDir = join(options.cwd, "data", "runs");
    mkdirSync(outDir, { recursive: true });
    const outputPath = join(outDir, `${definition.id}-${Date.now()}.md`);

    if (options.dryRun) {
      return {
        agentId: definition.id,
        backend: "mock",
        status: "dry-run",
        durationMs: Date.now() - start,
        outputPath,
        outputText: `[dry-run] mock backend would run ${definition.id}`,
      };
    }

    const briefing = extractBriefing(userMessage);
    const recommended = (briefing?.recommended_agents as Array<{ agent: string; reason: string }>) ?? [];
    const lines = [
      `# Mock agent run: ${definition.name}`,
      "",
      `_Generated by @li-langverse/cursor-agents mock backend (CI — no LLM)._`,
      "",
      "## Executive summary",
      `- Agent id: \`${definition.id}\``,
      `- Skills: ${definition.skills.join(", ") || "(none)"}`,
      `- Web search required in production: ${definition.needsWeb}`,
      `- Preflight: ${briefing ? "loaded from briefing JSON" : "no briefing parsed"}`,
      "",
      "## Recommended agents (from briefing)",
      ...recommended.map((r) => `- **${r.agent}**: ${r.reason}`),
      "",
      "## Mock actions (would be agent in production)",
      `1. Execute prompt: \`prompts/${definition.promptFile}\``,
      "2. File up to 3 issues with labels `explorer-finding` / `plan-needed`",
      "3. Post digest to roadmap or benchmarks",
      "",
      "## Status",
      "mock_finished",
    ];

    const text = lines.join("\n");
    writeFileSync(outputPath, text, "utf8");

    const jsonPath = outputPath.replace(/\.md$/, ".json");
    writeFileSync(
      jsonPath,
      JSON.stringify(
        {
          agentId: definition.id,
          backend: "mock",
          status: "finished",
          mock: true,
          recommended_agents: recommended,
        },
        null,
        2,
      ),
      "utf8",
    );

    return {
      agentId: definition.id,
      backend: "mock",
      status: "finished",
      durationMs: Date.now() - start,
      outputText: text,
      outputPath,
    };
  }
}

function extractBriefing(userMessage: string): Record<string, unknown> | null {
  const m = userMessage.match(/```json\n([\s\S]*?)\n```/);
  if (!m) return null;
  try {
    return JSON.parse(m[1]) as Record<string, unknown>;
  } catch {
    return null;
  }
}
