# shellcheck shell=bash
# Shared env for worker + UI dev processes (source from worker-dev.sh / dev-all.sh).
dev_export_li_env() {
  export LI_AUTO_START_ASYNC_SWARM="${LI_AUTO_START_ASYNC_SWARM:-0}"
  export LI_AUTO_START_SUPERVISOR="${LI_AUTO_START_SUPERVISOR:-0}"
  export LI_MAINTENANCE_STARTUP_DELAY_MS="${LI_MAINTENANCE_STARTUP_DELAY_MS:-15000}"
  export LI_LANE_STARTUP_DELAY_MS="${LI_LANE_STARTUP_DELAY_MS:-3000}"
  export LI_SWARM_RECONCILE_DEFER_MS="${LI_SWARM_RECONCILE_DEFER_MS:-2000}"
  export LI_WORKER_STARTUP_DEFER_MS="${LI_WORKER_STARTUP_DEFER_MS:-3000}"
  export LI_QUEUE_CACHE_MS="${LI_QUEUE_CACHE_MS:-20000}"
  export LI_QUEUE_WARM_MS="${LI_QUEUE_WARM_MS:-25000}"
  export LI_ASYNC_AGENT_INTERVAL_MS="${LI_ASYNC_AGENT_INTERVAL_MS:-90000}"
  export LI_PROACTIVE_AGENT_CADENCE_MS="${LI_PROACTIVE_AGENT_CADENCE_MS:-180000}"
  export LI_ASYNC_WORKER_ORCHESTRATOR="${LI_ASYNC_WORKER_ORCHESTRATOR:-1}"
  export LI_WORKER_HEARTBEAT_MS="${LI_WORKER_HEARTBEAT_MS:-3000}"
  export LI_REPORT_CACHE_MS="${LI_REPORT_CACHE_MS:-30000}"
  export LI_AGENT_DASHBOARD_PORT="${LI_AGENT_DASHBOARD_PORT:-9477}"
  export LI_DASHBOARD_UI_PORT="${LI_DASHBOARD_UI_PORT:-3000}"
  export LI_SDK_MAX_CONCURRENT="${LI_SDK_MAX_CONCURRENT:-2}"
  export BENCHMARKS_ROOT="${BENCHMARKS_ROOT:-}"
  export LI_LOCAL_CI_ROOT="${LI_LOCAL_CI_ROOT:-}"
  export LI_USE_LOCAL_CI="${LI_USE_LOCAL_CI:-1}"
  export LI_CONTROL_PLANE_STORE="${LI_CONTROL_PLANE_STORE:-supabase}"
}
