#!/usr/bin/env bash
# Ensure git worktree/clone for standby Supabase (offset ports) and start it.
# Writes .env.supabase.standby under the primary repo root.
#
#   LI_SUPABASE_ENSURE_QUIET=1  — minimal stdout
set -euo pipefail

_primary="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=lib/li-stack-env.sh
source "$_primary/scripts/lib/li-stack-env.sh"
# shellcheck source=lib/supabase-failover-ports.sh
source "$_primary/scripts/lib/supabase-failover-ports.sh"

_log() {
  [[ "${LI_SUPABASE_ENSURE_QUIET:-}" != "1" ]] && echo "$@"
}

_standby="$(li_supabase_standby_root "$_primary")"
_env_out="$_primary/.env.supabase.standby"

if [[ "${LI_STACK_SKIP_SUPABASE:-}" == "1" ]]; then
  exit 0
fi

if ! li_docker_ok; then
  echo "WARN: Docker not running — standby Supabase skipped" >&2
  exit 1
fi

_supabase_cmd() {
  if command -v supabase >/dev/null 2>&1; then
    supabase "$@"
  elif command -v npx >/dev/null 2>&1; then
    npx --yes supabase "$@"
  else
    return 127
  fi
}

if ! command -v supabase >/dev/null 2>&1 && ! command -v npx >/dev/null 2>&1; then
  echo "WARN: supabase CLI not found" >&2
  exit 1
fi

if [[ ! -d "$_standby" ]]; then
  _log "==> Supabase standby: create worktree at $_standby"
  if ! git -C "$_primary" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "ERROR: $_primary is not a git repo — set LI_SUPABASE_STANDBY_ROOT to an existing clone" >&2
    exit 1
  fi
  git -C "$_primary" worktree add "$_standby" HEAD
fi

if [[ -f "$_standby/supabase/config.toml" ]]; then
  li_supabase_patch_standby_config "$_standby/supabase/config.toml"
fi

_log "==> Supabase standby: start ($_standby)"
cd "$_standby"
if ! _supabase_cmd start; then
  echo "WARN: supabase start failed in standby worktree" >&2
  exit 1
fi

if ! _supabase_cmd migration up; then
  echo "WARN: standby migration up failed" >&2
  exit 1
fi

_api="$(li_supabase_standby_url)"
_db_port="$(li_supabase_standby_db_port)"
_project="$(basename "$_standby")"
_db_container="supabase_db_${_project}"
_jwt_secret=""
if li_docker inspect "$_db_container" >/dev/null 2>&1; then
  _jwt_secret="$(li_docker exec "$_db_container" printenv JWT_SECRET 2>/dev/null || true)"
fi

_out="$(
  SUPABASE_URL="$_api" SUPABASE_DB_PORT="$_db_port" JWT_SECRET="${_jwt_secret}" \
    node "$_primary/scripts/lib/supabase-local-keys.mjs" "${_jwt_secret}"
)"

{
  echo "# Auto-generated by scripts/ensure-supabase-standby.sh — do not commit"
  echo "# Regenerate: LI_SUPABASE_FAILOVER=1 npm run db:ensure"
  echo "$_out"
} >"$_env_out"

_log "==> Supabase standby: wrote $_env_out"

_sr="$(echo "$_out" | grep '^SUPABASE_SERVICE_ROLE_KEY=' | cut -d= -f2-)"
if [[ -n "$_sr" ]]; then
  _code="$(curl -sf -o /dev/null -w "%{http_code}" \
    -H "apikey: $_sr" -H "Authorization: Bearer $_sr" \
    "${_api}/rest/v1/" 2>/dev/null || echo "000")"
  if [[ "$_code" != "200" ]]; then
    echo "ERROR: standby REST not ready (HTTP ${_code})" >&2
    exit 1
  fi
  _log "==> Supabase standby: REST ready at ${_api}"
fi
