#!/usr/bin/env bash
# Start local Supabase, apply migrations, write .env.supabase (gitignored).
# Sourced by setup, keep-agents-running, start-stack.
#
#   LI_STACK_SKIP_SUPABASE=1     — skip entirely
#   LI_SUPABASE_DB_RESET=1       — supabase db reset (destructive)
#   LI_SUPABASE_ENSURE_QUIET=1   — no stdout except errors
set -euo pipefail

_ensure_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$_ensure_root"
# shellcheck source=lib/li-stack-env.sh
source "$_ensure_root/scripts/lib/li-stack-env.sh"
li_source_env_supabase "$_ensure_root" || true

_log() {
  if [[ "${LI_SUPABASE_ENSURE_QUIET:-}" != "1" ]]; then
    echo "$@"
  fi
}

if li_supabase_failover_enabled; then
  if li_apply_supabase_failover "$_ensure_root"; then
    _log "==> Supabase: failover active endpoint=${LI_SUPABASE_ACTIVE_ENDPOINT:-?} url=${SUPABASE_URL:-?}"
    exit 0
  fi
elif li_supabase_rest_ready; then
  _log "==> Supabase: REST already reachable at ${SUPABASE_URL}"
  exit 0
fi

if [[ "${LI_STACK_SKIP_SUPABASE:-}" == "1" ]]; then
  exit 0
fi

if [[ ! -f supabase/config.toml ]]; then
  echo "WARN: supabase/config.toml missing — disk cache only" >&2
  exit 0
fi

_supabase_cmd() {
  if command -v supabase >/dev/null 2>&1; then
    supabase "$@"
  elif command -v npx >/dev/null 2>&1; then
    npx --yes supabase "$@"
  else
    return 127
  fi
}

if ! command -v supabase >/dev/null 2>&1 && ! command -v npx >/dev/null 2>&1; then
  echo "WARN: supabase CLI not found (install or use npx) — disk cache only" >&2
  exit 0
fi

if ! li_docker_ok; then
  echo "WARN: Docker not running — Supabase skipped (disk cache only)" >&2
  exit 0
fi

_log "==> Supabase: start"
if ! _supabase_cmd start; then
  echo "WARN: supabase start failed" >&2
  exit 1
fi

if [[ "${LI_SUPABASE_DB_RESET:-}" == "1" ]]; then
  _log "==> Supabase: db reset (LI_SUPABASE_DB_RESET=1)"
  _supabase_cmd db reset
else
  _log "==> Supabase: apply local migrations (migration up)"
  if ! _supabase_cmd migration up; then
    echo "ERROR: supabase migration up failed — try: LI_SUPABASE_DB_RESET=1 npm run db:ensure" >&2
    exit 1
  fi
fi

API_URL="$(_supabase_cmd status -o json 2>/dev/null | node -e "
let d=''; process.stdin.on('data',c=>d+=c); process.stdin.on('end',()=>{
  try { console.log(JSON.parse(d).API_URL || 'http://127.0.0.1:54321'); }
  catch { console.log('http://127.0.0.1:54321'); }
});
" 2>/dev/null || echo "http://127.0.0.1:54321")"

# Container suffix matches project dir name (e.g. supabase_db_li-cursor-agents)
_project="$(basename "$_ensure_root")"
_db_container="supabase_db_${_project}"
_jwt_secret=""
if li_docker inspect "$_db_container" >/dev/null 2>&1; then
  _jwt_secret="$(li_docker exec "$_db_container" printenv JWT_SECRET 2>/dev/null || true)"
fi

_out="$(
  SUPABASE_URL="$API_URL" JWT_SECRET="${_jwt_secret}" \
    node "$_ensure_root/scripts/lib/supabase-local-keys.mjs" "${_jwt_secret}"
)"

_env_file="$_ensure_root/.env.supabase"
{
  echo "# Auto-generated by scripts/ensure-supabase.sh — do not commit"
  echo "# Regenerate: npm run db:ensure"
  echo "$_out"
} >"$_env_file"

_log "==> Supabase: wrote $_env_file"

# Wait for PostgREST (supervisor persist uses REST, not Postgres 54322)
_sr="$(echo "$_out" | grep '^SUPABASE_SERVICE_ROLE_KEY=' | cut -d= -f2-)"
if [[ -n "$_sr" ]]; then
  _ready=0
  for _i in $(seq 1 30); do
    _code="$(curl -sf -o /dev/null -w "%{http_code}" \
      -H "apikey: $_sr" -H "Authorization: Bearer $_sr" \
      "${API_URL}/rest/v1/" 2>/dev/null || echo "000")"
    if [[ "$_code" == "200" ]]; then
      _ready=1
      break
    fi
    sleep 1
  done
  if [[ "$_ready" != "1" ]]; then
    echo "ERROR: Supabase REST not ready after 30s (HTTP ${_code:-000}) — npm run db:probe" >&2
    exit 1
  fi
  _log "==> Supabase: REST ready at ${API_URL}"
fi

# Verify handoffs migration — older DBs missed swarm file (duplicate 20260517150000 version)
_handoffs_code="$(curl -sf -o /dev/null -w "%{http_code}" \
  -H "apikey: $_sr" -H "Authorization: Bearer $_sr" \
  "${API_URL}/rest/v1/agent_handoffs?select=handoff_id&limit=1" 2>/dev/null || echo "000")"
if [[ "$_handoffs_code" != "200" ]]; then
  echo "ERROR: public.agent_handoffs missing (HTTP ${_handoffs_code}) — run: npm run db:ensure" >&2
  echo "       If migrations are stuck: LI_SUPABASE_DB_RESET=1 npm run db:ensure" >&2
  exit 1
fi
_log "==> Supabase: agent_handoffs table OK"

_sessions_code="$(curl -sf -o /dev/null -w "%{http_code}" \
  -H "apikey: $_sr" -H "Authorization: Bearer $_sr" \
  "${API_URL}/rest/v1/research_sessions?select=session_id,hypotheses&limit=1" 2>/dev/null || echo "000")"
if [[ "$_sessions_code" != "200" ]]; then
  echo "ERROR: research_sessions.hypotheses missing (HTTP ${_sessions_code}) — run: npm run db:ensure" >&2
  exit 1
fi
_log "==> Supabase: research_sessions.hypotheses OK"

if li_supabase_failover_enabled; then
  if ! li_apply_supabase_failover "$_ensure_root"; then
    _log "==> Supabase: primary up; standby not probed (run ensure-supabase-standby if needed)"
  elif [[ "${LI_SUPABASE_ACTIVE_ENDPOINT:-}" == "standby" ]]; then
    _log "==> Supabase: failover selected standby after ensure"
  fi
fi
