import { researchLaneAgentsFromFactory } from "../research-goals/researcher-factory.js";
import type { AgentDefinition, AgentId, LegacyAgentId } from "../types.js";

/** Legacy briefing / fixture ids → canonical registry ids. */
export const AGENT_ALIASES: Record<LegacyAgentId, AgentId> = {
  plan_completion: "plan_verifier",
  ecosystem_explorer: "gap_explorer",
  pr_review: "pr_reviewer",
  numerics_research: "numerics_researcher",
};

export function canonicalAgentId(id: string): AgentId | undefined {
  const key = (AGENT_ALIASES[id as LegacyAgentId] ?? id) as AgentId;
  return AGENT_REGISTRY.some((a) => a.id === key) ? key : undefined;
}

export const AGENT_REGISTRY: AgentDefinition[] = [
  {
    id: "orchestrator",
    name: "Orchestrator",
    description: "Routes work from briefing; weekly ecosystem sweep.",
    category: "orchestration",
    promptFile: "agent-orchestrator.md",
    skills: ["explore-control-plane-db"],
    needsWeb: false,
    preflightKeys: ["briefing"],
  },
  {
    id: "plan_verifier",
    name: "Plan verifier",
    description: "Audits open master-plan / PH trackers vs reality; flags drift.",
    category: "governance",
    promptFile: "plan-verifier.md",
    skills: ["audit-plan-completion"],
    needsWeb: false,
    preflightKeys: ["plan_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "gap_explorer",
    name: "Gap explorer",
    description: "Ecosystem gaps: std, HPC libs, catalog, Reddit/web SOTA signals.",
    category: "ecosystem",
    promptFile: "gap-explorer.md",
    skills: ["explore-li-ecosystem"],
    needsWeb: true,
    preflightKeys: ["explorer", "ecosystem_audit", "briefing"],
  },
  {
    id: "implementation_gaps",
    name: "Implementation gaps",
    description: "Plan vs code drift; files issues for missing PH work.",
    category: "governance",
    promptFile: "implementation-gaps-agent.md",
    skills: ["explore-li-ecosystem", "audit-plan-completion", "agent-self-unblock", "run-goal-directed-loop"],
    needsWeb: true,
    preflightKeys: ["plan_audit", "explorer", "issue_triage", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "code_implementer",
    name: "Code implementer",
    description: "Implements gaps, bugs, and queue items; opens PRs via post-hook.",
    category: "governance",
    promptFile: "code-implementer.md",
    skills: ["explore-li-ecosystem", "audit-plan-completion", "agent-self-unblock", "run-goal-directed-loop"],
    needsWeb: false,
    preflightKeys: ["plan_audit", "explorer", "ci_bug_triage", "briefing"],
    repoWorkflow: true,
    guaranteedPush: true,
    cursorSdkMode: "agent",
  },
  {
    id: "bug_fixer",
    name: "Bug fixer",
    description: "Fixes CI failures (local-ci + GHA) and bug-labeled GitHub issues.",
    category: "governance",
    promptFile: "bug-fixer.md",
    skills: ["explore-li-ecosystem", "li-ecosystem-discipline", "agent-self-unblock"],
    needsWeb: false,
    preflightKeys: ["ci_bug_triage", "pr_program", "briefing"],
    repoWorkflow: true,
    guaranteedPush: true,
    cursorSdkMode: "debug",
  },
  {
    id: "security_auditor",
    name: "Security auditor",
    description: "Audits org repos against lic CVE/CWE catalog and security tests.",
    category: "security",
    promptFile: "security-auditor.md",
    skills: ["li-ecosystem-discipline", "security-offensive-research", "publish-research-whitepaper"],
    needsWeb: true,
    preflightKeys: ["security_cwe_audit", "cwe_feed_delta", "briefing"],
    repoWorkflow: true,
    guaranteedPush: true,
  },
  {
    id: "issue_planner",
    name: "Issue planner",
    description: "Turns plan-needed issues into scoped implementation plans.",
    category: "governance",
    promptFile: "issue-feature-planner.md",
    skills: ["plan-feature-from-issue"],
    needsWeb: false,
    preflightKeys: ["issue_triage", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "org_issue_triage",
    name: "Org issue triage",
    description:
      "Org-wide issue zero sprint: classify, implement, or close with auditable reason comments.",
    category: "governance",
    promptFile: "org-issue-triage-agent.md",
    skills: [],
    needsWeb: false,
    preflightKeys: ["briefing"],
    cursorSdkMode: "agent",
  },
  {
    id: "pr_branch_opener",
    name: "PR branch opener",
    description: "Opens PRs for pushed branches that have no open pull request yet.",
    category: "pull_requests",
    promptFile: "pr-branch-opener.md",
    skills: ["review-pr-alignment"],
    needsWeb: false,
    preflightKeys: ["merge_plan", "pr_program", "pr_branch_hygiene", "briefing"],
  },
  {
    id: "pr_alignment",
    name: "PR alignment",
    description: "Open PRs vs vision, roadmap, pillar order; closes superseded or outdated PRs.",
    category: "pull_requests",
    promptFile: "pr-alignment-agent.md",
    skills: ["review-pr-alignment"],
    needsWeb: false,
    preflightKeys: ["merge_plan", "pr_program", "pr_branch_hygiene", "briefing"],
  },
  {
    id: "pr_reviewer",
    name: "PR reviewer",
    description: "Standards review: proof, security, perf, release notes, philosophy.",
    category: "pull_requests",
    promptFile: "pr-reviewer.md",
    skills: ["merge-approved-pr", "review-pr-alignment"],
    needsWeb: false,
    preflightKeys: ["merge_plan", "pr_program", "briefing"],
  },
  {
    id: "pr_merger",
    name: "PR merger",
    description: "Merges PRs when reviewed, merge-approved, and CI gates pass.",
    category: "pull_requests",
    promptFile: "pr-merger.md",
    skills: ["plan-merge-queue", "merge-approved-pr"],
    needsWeb: false,
    preflightKeys: ["merge_plan", "pr_program", "briefing"],
  },
  {
    id: "numerics_researcher",
    name: "Numerics researcher",
    description: "Existing algorithms: Numerical Recipes, PETSc/Eigen, papers, journals.",
    category: "numerics",
    promptFile: "numerics-researcher.md",
    skills: ["research-li-numerics", "publish-research-whitepaper"],
    needsWeb: true,
    preflightKeys: ["ecosystem_audit", "explorer", "briefing"],
    guaranteedPush: true,
  },
  {
    id: "autoresearch",
    name: "Autonomous researcher",
    description: "Novel methods; bench vs SOTA; publish when improvement is proved.",
    category: "numerics",
    promptFile: "autoresearch.md",
    skills: ["numerics-autoresearch", "research-li-numerics"],
    needsWeb: true,
    preflightKeys: ["ecosystem_audit", "explorer", "briefing"],
    guaranteedPush: true,
  },
  {
    id: "bench_improver",
    name: "Benchmark improver",
    description: "Fixes red/near-limit rows in lic harness; ≤1.2× cpp policy.",
    category: "numerics",
    promptFile: "bench-improver.md",
    skills: ["research-li-numerics", "hpc-competitive-review"],
    needsWeb: false,
    preflightKeys: ["ecosystem_audit", "briefing"],
    guaranteedPush: true,
  },
  {
    id: "docs_maintainer",
    name: "Docs maintainer",
    description: "Missing live docs, handbook gaps; implements docs in org repos.",
    category: "platform",
    promptFile: "docs-maintainer.md",
    skills: ["explore-li-ecosystem"],
    needsWeb: false,
    preflightKeys: ["ecosystem_audit", "explorer", "briefing"],
    repoWorkflow: true,
    guaranteedPush: true,
  },
  {
    id: "ci_maintainer",
    name: "CI maintainer",
    description: "Missing org CI workflows; templates from lic/scripts/templates.",
    category: "platform",
    promptFile: "ci-maintainer.md",
    skills: [],
    needsWeb: false,
    preflightKeys: ["org_ci_audit", "ecosystem_audit", "briefing"],
    repoWorkflow: true,
    guaranteedPush: true,
    cursorSdkMode: "debug",
  },
  {
    id: "agent_kit_maintainer",
    name: "Agent-kit maintainer",
    description: "Scan org repos for roadmap agent-kit drift; isolated clone, sync, open PRs.",
    category: "platform",
    promptFile: "agent-kit-maintainer.md",
    skills: ["li-ecosystem-discipline"],
    needsWeb: false,
    preflightKeys: ["org_agent_kit_audit", "ecosystem_explorer", "briefing"],
    repoWorkflow: true,
  },
  {
    id: "org_repo_onboarder",
    name: "Org repo onboarder",
    description:
      "Discover new li-langverse GitHub repos and fan out CI, agent-kit, docs, and catalog handoffs.",
    category: "platform",
    promptFile: "org-repo-onboarder.md",
    skills: ["explore-li-ecosystem"],
    needsWeb: false,
    preflightKeys: [
      "org_new_repos_discovery",
      "org_ci_audit",
      "org_agent_kit_audit",
      "briefing",
    ],
    cursorSdkMode: "plan",
  },
  {
    id: "workspace_sweeper",
    name: "Workspace sweeper",
    description:
      "Fallback safety: commit/push/PR uncommitted work in sibling repos; document tests; restart control plane.",
    category: "platform",
    promptFile: "workspace-sweeper.md",
    skills: [],
    needsWeb: false,
    preflightKeys: ["workspace_dirty_sweep", "briefing"],
    workspaceSweep: true,
  },
  {
    id: "package_architect",
    name: "Package architect",
    description: "Semantic placement: extend existing package vs create monorepo/official PKG.",
    category: "governance",
    promptFile: "package-architect.md",
    skills: ["create-li-package", "explore-li-ecosystem"],
    needsWeb: false,
    preflightKeys: ["explorer", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "goal_researcher",
    name: "Goal researcher",
    description: "Domain goal-directed research (simulation, game, AI, web, CAD).",
    category: "ecosystem",
    promptFile: "goal-researcher.md",
    skills: ["explore-li-ecosystem", "publish-research-whitepaper"],
    needsWeb: true,
    preflightKeys: ["briefing"],
    cursorSdkMode: "agent",
  },
  {
    id: "proof_gap_researcher",
    name: "Proof gap researcher",
    description: "Hunts provability holes, G-* gaps, external trust boundaries.",
    category: "governance",
    promptFile: "proof-gap-researcher.md",
    skills: ["li-ecosystem-discipline"],
    needsWeb: false,
    preflightKeys: ["plan_audit", "briefing"],
    cursorSdkMode: "agent",
  },
  {
    id: "stdlib_researcher",
    name: "Stdlib researcher",
    description: "Deep std + li-std-* audit; packages to build vs improve.",
    category: "ecosystem",
    promptFile: "stdlib-researcher.md",
    skills: ["explore-li-ecosystem"],
    needsWeb: true,
    preflightKeys: ["explorer", "briefing"],
    cursorSdkMode: "agent",
  },
  {
    id: "swarm_observer",
    name: "Swarm observer",
    description:
      "Meta-agent: audits swarm health, failed handoffs, prompt/supervisor gaps; proposes self-healing fixes.",
    category: "platform",
    promptFile: "swarm-observer.md",
    skills: ["explore-control-plane-db"],
    needsWeb: false,
    preflightKeys: ["briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "ecosystem_grader",
    name: "Ecosystem grader",
    description:
      "Scores swarm/ecosystem quality from briefing, goal-directed snapshot, and run samples; recommends meta fixes.",
    category: "platform",
    promptFile: "ecosystem-grader.md",
    skills: ["explore-control-plane-db"],
    needsWeb: false,
    preflightKeys: ["briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "docs_ui_tester",
    name: "Docs UI tester",
    description: "Visual audit for MkDocs/docs: screenshots, axe, baselines; files ui_remediation issues.",
    category: "ux",
    promptFile: "docs-ui-tester.md",
    skills: ["explore-li-ecosystem"],
    needsWeb: false,
    preflightKeys: ["ui_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "docs_ux_tester",
    name: "Docs UX tester",
    description: "Docs journeys vs SOTA; files ux_remediation issues for implementers.",
    category: "ux",
    promptFile: "docs-ux-tester.md",
    skills: ["explore-li-ecosystem"],
    needsWeb: true,
    preflightKeys: ["ux_audit", "ui_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "gui_ui_tester",
    name: "GUI UI tester",
    description: "Visual audit for dashboard/SDL/gui-gen; pixel diff and axe.",
    category: "ux",
    promptFile: "gui-ui-tester.md",
    skills: ["studio-design-review", "studio-accessibility-web-quality"],
    needsWeb: false,
    preflightKeys: ["ui_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "gui_ux_tester",
    name: "GUI UX tester",
    description: "GUI flows vs SOTA; empty states and journey friction.",
    category: "ux",
    promptFile: "gui-ux-tester.md",
    skills: ["studio-agentic-ux", "studio-ui-ux-rubric", "studio-design-review"],
    needsWeb: true,
    preflightKeys: ["ux_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "tui_ui_tester",
    name: "TUI UI tester",
    description: "Terminal UI captures for tui_app and tui_gen targets.",
    category: "ux",
    promptFile: "tui-ui-tester.md",
    skills: [],
    needsWeb: false,
    preflightKeys: ["ui_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "tui_ux_tester",
    name: "TUI UX tester",
    description: "TUI journeys vs Textual/Bubble Tea SOTA.",
    category: "ux",
    promptFile: "tui-ux-tester.md",
    skills: [],
    needsWeb: true,
    preflightKeys: ["ux_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "studio_ui_ux_builder",
    name: "Studio UI/UX builder",
    description:
      "Implements Li Studio native UI/render slices; captures screenshots/video; benchmarks particles/memory; scores PH-UX each iteration.",
    category: "ux",
    promptFile: "studio-ui-ux-builder.md",
    skills: [
      "explore-li-ecosystem",
      "studio-design-system-generator",
      "studio-design-review",
      "studio-agentic-ux",
      "studio-accessibility-web-quality",
      "studio-ui-ux-rubric",
    ],
    needsWeb: true,
    preflightKeys: ["briefing"],
    repoWorkflow: true,
    guaranteedPush: true,
    cursorSdkMode: "agent",
  },
  {
    id: "ga_unit_auditor",
    name: "G&A unit auditor",
    description: "Org swarm: unit-test coverage per repo — exports, edge cases, std 100% gate.",
    category: "governance",
    promptFile: "ga-unit-auditor.md",
    skills: ["ga-unit-testing", "li-ecosystem-discipline"],
    needsWeb: false,
    preflightKeys: ["briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "ga_integration_auditor",
    name: "G&A integration auditor",
    description: "Org swarm: cross-module and API integration test coverage per repo.",
    category: "governance",
    promptFile: "ga-integration-auditor.md",
    skills: ["ga-integration-testing", "li-ecosystem-discipline"],
    needsWeb: false,
    preflightKeys: ["briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "ga_e2e_auditor",
    name: "G&A E2E auditor",
    description: "Org swarm: end-to-end flows per README use case; Playwright / li-tests.",
    category: "governance",
    promptFile: "ga-e2e-auditor.md",
    skills: ["ga-e2e-testing", "li-ecosystem-discipline"],
    needsWeb: false,
    preflightKeys: ["briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "ga_gui_auditor",
    name: "G&A GUI / visual auditor",
    description: "Org swarm: visual QA, a11y, Figma/Magic Patterns parity for UI repos.",
    category: "ux",
    promptFile: "ga-gui-auditor.md",
    skills: ["ga-visual-qa", "studio-design-review", "studio-accessibility-web-quality"],
    needsWeb: true,
    preflightKeys: ["ui_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "ga_soc_auditor",
    name: "G&A SOC auditor",
    description: "Org swarm: security compliance, CVE catalog, SOC2-relevant controls per repo.",
    category: "security",
    promptFile: "ga-soc-auditor.md",
    skills: ["ga-soc-compliance", "security-offensive-research", "li-ecosystem-discipline"],
    needsWeb: true,
    preflightKeys: ["security_cwe_audit", "briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "ga_docs_auditor",
    name: "G&A documentation auditor",
    description: "Org swarm: README/API/runbook completeness; Li brand via Magic Patterns MCP.",
    category: "platform",
    promptFile: "ga-docs-auditor.md",
    skills: ["ga-documentation", "li-ecosystem-discipline"],
    needsWeb: true,
    preflightKeys: ["briefing"],
    cursorSdkMode: "plan",
  },
  {
    id: "world_studio_builder",
    name: "World Studio builder",
    description:
      "Executes WORLD-STUDIO-MASTER-PLAN.md in native Li � shell, sim, agent MCP, canvas, exports � until plan-loop todos are done.",
    category: "platform",
    promptFile: "world-studio-builder.md",
    skills: [
      "explore-li-ecosystem",
      "agent-self-unblock",
      "run-goal-directed-loop",
      "studio-design-review",
      "studio-agentic-ux",
      "studio-ui-ux-rubric",
    ],
    needsWeb: false,
    preflightKeys: ["briefing"],
    repoWorkflow: true,
    guaranteedPush: true,
    cursorSdkMode: "agent",
  },
];

export function getAgent(id: string): AgentDefinition | undefined {
  const canonical = canonicalAgentId(id);
  if (!canonical) return undefined;
  return AGENT_REGISTRY.find((a) => a.id === canonical);
}

/** Factory-mapped research agents missing from AGENT_REGISTRY (empty = OK). */
export function missingResearchFactoryAgents(): AgentId[] {
  const missing: AgentId[] = [];
  for (const id of researchLaneAgentsFromFactory()) {
    if (!getAgent(id)) missing.push(id);
  }
  return missing;
}

export function allAgentIds(): Set<string> {
  const s = new Set<string>(AGENT_REGISTRY.map((a) => a.id));
  for (const legacy of Object.keys(AGENT_ALIASES)) s.add(legacy);
  return s;
}

export function isKnownAgent(id: string): boolean {
  return canonicalAgentId(id) !== undefined;
}

export function listAgentsPublic(): Array<{
  id: AgentId;
  name: string;
  description: string;
  category: string;
  needsWeb: boolean;
  skills: string[];
}> {
  return AGENT_REGISTRY.map(({ id, name, description, category, needsWeb, skills }) => ({
    id,
    name,
    description,
    category,
    needsWeb,
    skills,
  }));
}

